version: '2.1'
services:
  gateway:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
    - redis
    env_file: .env
  dev:
    image: ${IMAGE_NAME}
    depends_on:
    - redis
    ports:
      - "8080:8080"
      - "8090:8090"
    volumes:
      - .:/opt/app-root/src
    env_file: .env
    environment:
      TEST_NGINX_BINARY: openresty
      TEST_NGINX_REDIS_HOST: redis
    dns_search:
      - example.com
  test:
    image: ${IMAGE_NAME:-apicast-test}
    depends_on:
      - gateway
    entrypoint: ""
    dns: 127.0.0.1
    environment:
      APICAST_MANAGEMENT_API: debug
    dns_search:
      - example.com
  prove:
    image: ${IMAGE_NAME:-apicast-test}
    user: root
    entrypoint: "bash -ec"
    environment:
      TEST_NGINX_BINARY: openresty
      TEST_NGINX_REDIS_HOST: redis
    command: "'$$TEST_NGINX_BINARY -V; cd ; make prove; exit $$?'"
    dns_search:
      - example.com
    depends_on:
      - redis
    volumes_from:
    - container:${COMPOSE_PROJECT_NAME}-source
  redis:
    image: redis
  keycloak:
    image: jboss/keycloak:3.1.0.Final
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_LOGLEVEL: INFO
    ports:
      - "8080"
